name: github-action-for-test
on: [push]
jobs:
  echo-hello:
    - name: Alpine Probe & Echo
      uses: Kaizhe/alpine-echo@v1.0.0
      with:
        message: default is Hello World?

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm test
